apiVersion: v1
kind: Service
metadata:
  name: {{ include "lab-17-nov.fullname" . }}
  labels:
    {{- include "lab-17-nov.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ include "lab-17-nov.fullname" . }}
  selector:
    {{- include "lab-17-nov.selectorLabels" . | nindent 4 }}
